CREATE TABLE IF NOT EXISTS `device_log` (
  `log_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `device_id` smallint(6) NOT NULL,
  `log_engine` tinyint(3) unsigned NOT NULL,
  `log_speed` smallint(6) NOT NULL,
  `log_gsm` smallint(6) NOT NULL,
  `log_gps` smallint(6) NOT NULL,
  `location_lat` decimal(10,6) NOT NULL,
  `location_lng` decimal(10,6) NOT NULL,
  `state_bit_0` tinyint(3) unsigned NOT NULL,
  `state_bit_1` tinyint(3) unsigned NOT NULL,
  `state_bit_2` tinyint(3) unsigned NOT NULL,
  `state_bit_3` tinyint(3) unsigned NOT NULL,
  `state_bit_4` tinyint(3) unsigned NOT NULL,
  `state_bit_5` tinyint(3) unsigned NOT NULL,
  `state_bit_6` tinyint(3) unsigned NOT NULL,
  `state_bit_7` tinyint(3) unsigned NOT NULL,
  `state_bit_8` tinyint(3) unsigned NOT NULL,
  `state_bit_9` tinyint(3) unsigned NOT NULL,
  `state_bit_10` tinyint(3) unsigned NOT NULL,
  `state_bit_11` tinyint(3) unsigned NOT NULL,
  `state_bit_12` tinyint(3) unsigned NOT NULL,
  `state_bit_13` tinyint(3) unsigned NOT NULL,
  `state_bit_14` tinyint(3) unsigned NOT NULL,
  `state_bit_15` tinyint(3) unsigned NOT NULL,
  `input_ad_1` decimal(8,2) NOT NULL,
  `input_ad_2` decimal(8,2) NOT NULL,
  `input_ad_3` decimal(8,2) NOT NULL,
  `input_ad_4` decimal(8,2) NOT NULL,
  `input_ad_5` decimal(8,2) NOT NULL,
  `update_time` datetime NOT NULL,
  PRIMARY KEY (`log_id`),
  UNIQUE KEY `device_id_update_time` (`device_id`,`update_time`)
) ENGINE=MyISAM AUTO_INCREMENT=10000001 DEFAULT CHARSET=utf8;
